# Generated by Django 3.1.3 on 2020-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
